from processors import *

#words = modifier(open('test.txt', 'r').read(), 'all')
#words1 = modifier(open('test1.txt', 'r').read(), 'all')
words2 = modifier(open('test2.txt', 'r').read(), 'all')
#words3 = modifier(open('test3.txt', 'r').read(), 'all')
#words4 = modifier(open('test4.txt', 'r').read(), 'cities')
print(counter(words2))
#print(words)
#print(CityRemover(words))
#print('\n'.join(generator(words, words1, words2)))
#print(modifier(open('test1.txt', 'r').read(), '+prep'))
#print('\n'.join(lemma(words3)))
#print(words3)
#print(declension(words2))